package util

// Edit if desired. Code generated by "go-fuzz-fill-utils ./jsonapi/".

import (
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/infosecual/go-fuzz-fill-utils/fuzzer"
	"github.com/offchainlabs/nitro/util/jsonapi"
)

func Fuzz_PreimagesMapJson_MarshalJSON(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var inner map[common.Hash][]byte
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&inner)

		m := jsonapi.NewPreimagesMapJson(inner)
		m.MarshalJSON()
	})
}

func Fuzz_PreimagesMapJson_UnmarshalJSON(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var inner map[common.Hash][]byte
		var d2 []byte
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&inner, &d2)

		m := jsonapi.NewPreimagesMapJson(inner)
		m.UnmarshalJSON(d2)
	})
}

func Fuzz_NewPreimagesMapJson(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var inner map[common.Hash][]byte
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&inner)

		jsonapi.NewPreimagesMapJson(inner)
	})
}
