package util

// Edit if desired. Code generated by "go-fuzz-fill-utils ./pretty/".

import (
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/infosecual/go-fuzz-fill-utils/fuzzer"
	"github.com/offchainlabs/nitro/util/pretty"
)

func Fuzz_FirstFewBytes(f *testing.F) {
	f.Fuzz(func(t *testing.T, b []byte) {
		pretty.FirstFewBytes(b)
	})
}

func Fuzz_FirstFewChars(f *testing.F) {
	f.Fuzz(func(t *testing.T, s string) {
		pretty.FirstFewChars(s)
	})
}

func Fuzz_PrettyBytes(f *testing.F) {
	f.Fuzz(func(t *testing.T, b []byte) {
		pretty.PrettyBytes(b)
	})
}

func Fuzz_PrettyHash(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var hash common.Hash
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&hash)

		pretty.PrettyHash(hash)
	})
}
