package chaininfofuzz

// Edit if desired. Code generated by "go-fuzz-fill-utils ./daserver/".

import (
	"context"
	"testing"

	"github.com/infosecual/go-fuzz-fill-utils/fuzzer"
)

func Fuzz_L1ReaderCloser_Close(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var c *main.L1ReaderCloser
		var _x2 context.Context
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&c, &_x2)
		if c == nil {
			return
		}

		c.Close(_x2)
	})
}

func Fuzz_L1ReaderCloser_String(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var c *main.L1ReaderCloser
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&c)
		if c == nil {
			return
		}

		c.String()
	})
}
