package util

// Edit if desired. Code generated by "go-fuzz-fill-utils ./sharedmetrics/".

import (
	"testing"

	"github.com/infosecual/go-fuzz-fill-utils/fuzzer"
	"github.com/offchainlabs/nitro/arbutil"
	"github.com/offchainlabs/nitro/util/sharedmetrics"
)

func Fuzz_UpdateSequenceNumberGauge(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var sequenceNumber arbutil.MessageIndex
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&sequenceNumber)

		sharedmetrics.UpdateSequenceNumberGauge(sequenceNumber)
	})
}

func Fuzz_UpdateSequenceNumberInBlockGauge(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var sequenceNumber arbutil.MessageIndex
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&sequenceNumber)

		sharedmetrics.UpdateSequenceNumberInBlockGauge(sequenceNumber)
	})
}
