package chaininfofuzz

// Edit if desired. Code generated by "go-fuzz-fill-utils ./util/".

import (
	"context"
	"math/big"
	"testing"

	"github.com/infosecual/go-fuzz-fill-utils/fuzzer"
	"github.com/offchainlabs/nitro/cmd/genericconf"
	"github.com/offchainlabs/nitro/cmd/util"
)

func Fuzz_GetL2ChainInfoIpfsFile(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var ctx context.Context
		var l2ChainInfoIpfsUrl string
		var l2ChainInfoIpfsDownloadPath string
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&ctx, &l2ChainInfoIpfsUrl, &l2ChainInfoIpfsDownloadPath)

		util.GetL2ChainInfoIpfsFile(ctx, l2ChainInfoIpfsUrl, l2ChainInfoIpfsDownloadPath)
	})
}

func Fuzz_OpenWallet(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var description string
		var walletConfig *genericconf.WalletConfig
		var chainId *big.Int
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&description, &walletConfig, &chainId)
		if walletConfig == nil || chainId == nil {
			return
		}

		util.OpenWallet(description, walletConfig, chainId)
	})
}
