package arbcompressfuzz

// Edit if desired. Code generated by "go-fuzz-fill-utils ./arbcompress/".

import (
        "testing"

        "github.com/offchainlabs/nitro/arbcompress"
)

func Fuzz_CompressFast(f *testing.F) {
        f.Fuzz(func(t *testing.T, input []byte) {
                arbcompress.CompressFast(input)
        })
}

func Fuzz_CompressWell(f *testing.F) {
        f.Fuzz(func(t *testing.T, input []byte) {
                arbcompress.CompressWell(input)
        })
}

func Fuzz_Decompress(f *testing.F) {
        f.Fuzz(func(t *testing.T, input []byte, maxSize int) {
                arbcompress.Decompress(input, maxSize)
        })
}
